openapi: 3.2.0
info:
  title: Ant Media Server Management Panel REST File System Status…
  description: Ant Media Server Management Panel REST API
  contact:
    name: Ant Media Info
    url: https://antmedia.io
    email: contact@antmedia.io
  license:
    name: Apache 2.0
    url: http://www.apache.org
  version: v2.0
tags:
- name: File System Status
paths:
  /v2/file-system-status:
    get:
      summary: Gets system file status
      operationId: getFileSystemInfo
      responses:
        '200':
          description: Successful operation
      tags:
      - File System Status
externalDocs:
  description: External Docs
  url: https://antmedia.io
