openapi: 3.0.1
info:
  title: Ant Media Server REST API Reference Broadcasts Push Notification API
  description: Ant Media Server REST API Reference
  contact:
    name: Ant Media Info
    url: https://antmedia.io
    email: contact@antmedia.io
  license:
    name: Apache 2.0
    url: http://www.apache.org
  version: V2.0
servers:
- url: https://test.antmedia.io:5443/Sandbox/rest/
  description: test server
tags:
- name: Push Notification
paths:
  /v2/push-notification/subscriber-auth-token:
    get:
      operationId: getSubscriberAuthenticationToken
      parameters:
      - name: subscriberId
        in: query
        schema:
          type: string
      - name: timeoutSeconds
        in: query
        schema:
          type: integer
          format: int32
      responses:
        default:
          description: default response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Result'
      tags:
      - Push Notification
  /v2/push-notification/subscribers:
    post:
      operationId: sendPushNotification
      parameters:
      - name: serviceName
        in: query
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PushNotificationToSubscribers'
      responses:
        default:
          description: default response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Result'
      tags:
      - Push Notification
  /v2/push-notification/topics/{topic}:
    post:
      operationId: sendPushNotification_1
      parameters:
      - name: topic
        in: path
        required: true
        schema:
          type: string
      - name: serviceName
        in: query
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              type: string
      responses:
        default:
          description: default response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Result'
      tags:
      - Push Notification
components:
  schemas:
    PushNotificationToSubscribers:
      type: object
      properties:
        subscribers:
          type: array
          items:
            type: string
        jsonMessage:
          type: string
    Result:
      type: object
      properties:
        success:
          type: boolean
          description: The result of the operation
        message:
          type: string
          description: The message of the operation result
        dataId:
          type: string
          description: The id of the record if operation is about adding a record
        errorId:
          type: integer
          description: The id of error of the operation result
          format: int32
      description: The basic result class
externalDocs:
  url: https://antmedia.io
