openapi: 3.2.0
info:
  title: Ant Media Server Management Panel REST Live Clients Size API
  description: Ant Media Server Management Panel REST API
  contact:
    name: Ant Media Info
    url: https://antmedia.io
    email: contact@antmedia.io
  license:
    name: Apache 2.0
    url: http://www.apache.org
  version: v2.0
tags:
- name: Live Clients Size
paths:
  /v2/live-clients-size:
    get:
      summary: Returns total number of live streams
      operationId: getTotalLiveStreamSize
      responses:
        '200':
          description: Successful operation
      tags:
      - Live Clients Size
externalDocs:
  description: External Docs
  url: https://antmedia.io
