openapi: 3.2.0
info:
  title: Ant Media Server Management Panel REST Cluster API
  description: Ant Media Server Management Panel REST API
  contact:
    name: Ant Media Info
    url: https://antmedia.io
    email: contact@antmedia.io
  license:
    name: Apache 2.0
    url: http://www.apache.org
  version: v2.0
tags:
- name: Cluster
paths:
  /v2/cluster/node/{id}:
    delete:
      operationId: deleteNode
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        default:
          description: default response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Result'
      tags:
      - Cluster
      summary: Delete node
      x-summary-source: derived
  /v2/cluster/node-count:
    get:
      operationId: getNodeCount
      responses:
        default:
          description: default response
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/SimpleStat'
      tags:
      - Cluster
      summary: Get node count
      x-summary-source: derived
  /v2/cluster/nodes/{offset}/{size}:
    get:
      operationId: getNodeList
      parameters:
      - name: offset
        in: path
        required: true
        schema:
          type: integer
          format: int32
      - name: size
        in: path
        required: true
        schema:
          type: integer
          format: int32
      responses:
        default:
          description: default response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ClusterNode'
      tags:
      - Cluster
      summary: Get node list
      x-summary-source: derived
  /v2/cluster/node/{id}/note:
    put:
      operationId: updateNodeNote
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      - name: note
        in: query
        schema:
          type: string
      responses:
        default:
          description: default response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Result'
      tags:
      - Cluster
      summary: Update node note
      x-summary-source: derived
  /cluster/deleteNode/{id}:
    get:
      operationId: deleteNode_1
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        default:
          description: default response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Result'
      tags:
      - Cluster
      summary: Delete node 1
      x-summary-source: derived
  /cluster/node-count:
    get:
      operationId: getNodeCount_1
      responses:
        default:
          description: default response
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/SimpleStat'
      tags:
      - Cluster
      summary: Get node count 1
      x-summary-source: derived
  /cluster/nodes/{offset}/{size}:
    get:
      operationId: getNodeList_1
      parameters:
      - name: offset
        in: path
        required: true
        schema:
          type: integer
          format: int32
      - name: size
        in: path
        required: true
        schema:
          type: integer
          format: int32
      responses:
        default:
          description: default response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ClusterNode'
      tags:
      - Cluster
      summary: Get node list 1
      x-summary-source: derived
  /cluster/node/{id}/note:
    put:
      operationId: updateNodeNote_1
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      - name: note
        in: query
        schema:
          type: string
      responses:
        default:
          description: default response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Result'
      tags:
      - Cluster
      summary: Update node note 1
      x-summary-source: derived
components:
  schemas:
    SimpleStat:
      type: object
      properties:
        number:
          type: integer
          description: the stat value
          format: int64
      description: Simple generic statistics class to return single values
    ClusterNode:
      type: object
      properties:
        id:
          type: string
        ip:
          type: string
        lastUpdateTime:
          type: integer
          format: int64
        memory:
          type: string
        cpu:
          type: string
        dbQueryAveargeTimeMs:
          type: integer
          format: int32
        note:
          type: string
        status:
          type: string
    Result:
      type: object
      properties:
        success:
          type: boolean
          description: The result of the operation
        message:
          type: string
          description: The message of the operation result
        dataId:
          type: string
          description: The id of the record if operation is about adding a record
        errorId:
          type: integer
          description: The id of error of the operation result
          format: int32
      description: The basic result class
externalDocs:
  description: External Docs
  url: https://antmedia.io
