openapi: 3.2.0
info:
  title: Ant Media Server Management Panel REST Applications Info API
  description: Ant Media Server Management Panel REST API
  contact:
    name: Ant Media Info
    url: https://antmedia.io
    email: contact@antmedia.io
  license:
    name: Apache 2.0
    url: http://www.apache.org
  version: v2.0
tags:
- name: Applications Info
paths:
  /v2/applications-info:
    get:
      summary: Gets application info
      operationId: getApplicationInfo
      responses:
        '200':
          description: Successful operation
      tags:
      - Applications Info
externalDocs:
  description: External Docs
  url: https://antmedia.io
