openapi: 3.2.0
info:
  title: Ant Media Server Management Panel REST Cpu Status API
  description: Ant Media Server Management Panel REST API
  contact:
    name: Ant Media Info
    url: https://antmedia.io
    email: contact@antmedia.io
  license:
    name: Apache 2.0
    url: http://www.apache.org
  version: v2.0
tags:
- name: Cpu Status
paths:
  /v2/cpu-status:
    get:
      summary: Returns system cpu load, process cpu load and process cpu time
      operationId: getCPUInfo
      responses:
        '200':
          description: Successful operation
      tags:
      - Cpu Status
externalDocs:
  description: External Docs
  url: https://antmedia.io
